version: '3.8'
services:
  poi-data-postgres:
    build: .
    container_name: POI
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: POIRawData
    ports:
      - "5432:5432"
    volumes:
      - poi-raw-data:/var/lib/postgresql/data

volumes:
  poi-raw-data: