apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: poi-raw-data
  name: poi-raw-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
