FROM postgis/postgis:16-3.5

# Update packages and install all dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    cmake \
    gnupg \
    wget \
    build-essential \
    postgresql-server-dev-16 \
    gcc \
    make \
    pgxnclient \
    libssl-dev \
    libcurl4-openssl-dev \
    postgresql-16-h3 \
    && rm -rf /var/lib/apt/lists/*

# Create a directory for the data
RUN mkdir -p /var/lib/postgresql/data && \
    chown -R postgres:postgres /var/lib/postgresql/data && \
    chmod 700 /var/lib/postgresql/data

USER postgres

# Expose PostgreSQL port
EXPOSE 5432

# Set the default command to run PostgreSQL
CMD ["postgres"]